### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by Leeuwenkasteel** [tanthammar/tall-forms#101]
Hello,
I realy like your packages, but when i updated to version 8 there is a problem with the languages files. I see tf::form.alerts.updated-success instead of The form was saved successfully.

**Comment by tanthammar** [comment]
Hi. Thank you!
Did you publish the new language files?
Have you merged the updated config?
Cleared cache/config?

**Comment by tanthammar** [comment]
Also which language and fallback Lang have you set in config?

**Comment by Leeuwenkasteel** [comment]
That was it, I have set my  fallback on Dutch. I put it back to EN and it works fine

**Comment by simonbuehler** [comment]
the problem is that in https://github.com/laravel/framework/blob/c62385a23c639742b3b74a4a78640da25e6b782b/src/Illuminate/Translation/FileLoader.php#L103 the language overrides are searched in 
`/var/www/test/resources/lang/vendor/`**tf**`/de/form.php` while they get published to
`/var/www/test/resources/lang/vendor/`**tall-forms**`/de/form.php` so they are not found!

please publish to the *namespaced* folder
