### ISSUE TITLE
input type date not fill value

### ISSUE THREAD

**Issue by jouniikaheimo** [tanthammar/tall-forms#17]
I think my edit form is something wrong input type date not fill value only show m.d.y.
 i can pick date again but old values not show?

**Comment by tanthammar** [comment]
Can you paste your component code here please.
Also which version do you have installed.

**Comment by tanthammar** [comment]
Also did you see this? https://github.com/tanthammar/tall-forms/wiki/Field-Types#important-for-date-inputs

**Comment by tanthammar** [comment]
If your browser shows m.d.y you could try to cast the date to that format. 
Date formatting can be complicated if you serve the site for multiple time formats.

**Comment by jouniikaheimo** [comment]
> Can you paste your component code here please.
> Also which version do you have installed.

**Comment by jouniikaheimo** [comment]
datetime-local not working all browsers... I use lasted version and that date input format not fixed issue.. i think need found some datetimepicker what working alpinejs...

**Comment by tanthammar** [comment]
How do you cast the date in your model and in the form component?

**Comment by tanthammar** [comment]
Please also post your component code.

**Comment by tanthammar** [comment]
I am closing this due to lack of response. Please reopen if you want to discuss the topic again.

**Comment by PieterxJan** [comment]
Hi, sorry to reopen an old issue, but my question is closely related to this one. 

I have created an input field `due_date` of type datetime-local. I've used the default() method to set a default value, and that works, in the correct format (`'Y-m-d\TH:i'`).

But when I open up a form with an existing value, it doesn't fill the value, I guess because the original attribute returns a Carbon instance?

I've tried following steps:
- Defining the default format in the cast
```php
protected $casts = [
    'due_date' => 'datetime:Y-m-d\TH:i',
];
```

- Manually trying to override the due_date value just before creating the fields
```php
protected function fields(): array
{
    if ($this->model && $this->model->due_date) {
        $this->model->due_date = $this->model->due_date->format('Y-m-d\TH:i');
    }

    return [
        Input::make('Title', 'title')->rules('required'),
        Input::make('Due date', 'due_date')
            ->type('datetime-local')
            ->default(now()->format('Y-m-d\TH:i'))
            ->rules('required'),
    ];
}
```

- Created a mutator that returns the date as a formatted string
```php
public function getDueDateAttribute($value)
{
    return $value?->format('Y-m-d\TH:i');
}
```

None of the above steps resolved the issue. When opening a modal with a model attached to it, the Due date field is empty. Any ideas of actions I can take to fix this?

**Comment by tanthammar** [comment]
Can you try this. 

```php
protected function beforeFormProperties()
{
      $this->model->due_date = $this->model->due_date->toDateTimeLocalString('minute');
}
```

The default can also change to `->default(now()->toDateTimeLocalString('minute'))`

If it works you can change your cast to:
```php
protected $casts = [
    'due_date' => 'datetime',
];
```

If it still doesn't work it must be something with your browser language that requires another format for the date input. The browser is what sets which dateformat you should cast to.

**Comment by PieterxJan** [comment]
Hi Tina,

First of all, thanks for the quick response. 

My problem wasn't resolved with your suggested answer but it did point me in the right direction. I have fixed my issue in the following way: 

```php
protected function setFormProperties()
{
    $this->form_data = $this->model->only($this->firstLevelFieldNames());
    if ($this->form_data['due_date'] && $this->form_data['due_date'] instanceof Carbon) {
        $this->form_data['due_date'] = $this->form_data['due_date']->format('Y-m-d\TH:i');
    }
    $this->setFieldValues($this->getFieldsFlat());
}

protected function fields(): array
{
    return [
        Input::make('Subject', 'title')->rules('required'),
        Input::make('Due date', 'due_date')
            ->type('datetime-local')
            ->default(now()->toDateTimeLocalString('minute'))
            ->rules('required'),
        Textarea::make('Notes', 'notes')->rows(4)->rules('required'),
    ];
}
```

I could not change the due_date in the `beforeFormProperties()` method, because when `$this->model->only(...)` gets called, it tries to parse the date (because of the $casts array on the model). And since I can't remove that cast for other purposes, that wasn't an option. 

A more logical solution would be to use the `afterFormProperties()` method, but for some unknown reason, every logic I put in there wasn't executed, not even `die()` or `var_dump()`. So that made me override the `setFormProperties()` method and it works :). 

Thanks for the help!
